import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart, Download, FileSpreadsheet, FileText, Plus } from 'lucide-react';
import reportService from '../services/report.service';
import { PageHeader } from '../components/ui/page-header';
import { DataTable } from '../components/ui/data-table';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Select } from '../components/ui/select';
import { Label } from '../components/ui/label';
import { Modal } from '../components/ui/modal';
import { Alert } from '../components/ui/alert';
import { useToast } from '../components/ui/toast';
import { usePermission } from '../hooks/use-permission';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // Modal state
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [reportType, setReportType] = useState('inventory');
  const [isGenerating, setIsGenerating] = useState(false);
  
  const canManage = usePermission(['admin', 'manager']);
  const { toast } = useToast();

  const fetchReports = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await reportService.getReports();
      setReports(res.data?.items || res.data || []);
    } catch (err) {
      setError(err?.response?.data?.error?.message || 'Failed to load reports from server.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      await reportService.generateReport(reportType, {});
      toast({ title: 'Report generated', description: 'Your new report is ready.', variant: 'success' });
      setIsModalOpen(false);
      fetchReports();
    } catch (err) {
      toast({ title: 'Failed to generate report', description: err?.response?.data?.error?.message || err.message, variant: 'error' });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async (reportId, format) => {
    try {
      await reportService.downloadReport(reportId, format);
      toast({ title: 'Download started', description: `Downloading report in ${format.toUpperCase()} format.`, variant: 'success' });
    } catch (err) {
      toast({ title: 'Download failed', description: err.message, variant: 'error' });
    }
  };

  const columns = useMemo(() => [
    {
      key: 'name',
      header: 'Report Name',
      sortable: true,
      render: (row) => (
        <div className="flex items-center gap-2">
          <BarChart className="h-4 w-4 text-muted-foreground" />
          <span className="font-medium">{row.name}</span>
        </div>
      ),
    },
    {
      key: 'type',
      header: 'Type',
      sortable: true,
      render: (row) => (
        <Badge variant="secondary" className="capitalize">
          {row.type}
        </Badge>
      ),
    },
    {
      key: 'generatedBy',
      header: 'Generated By',
      className: 'hidden sm:table-cell',
      headerClassName: 'hidden sm:table-cell',
      render: (row) => <span className="text-muted-foreground">{row.generatedBy?.name || 'System'}</span>,
    },
    {
      key: 'createdAt',
      header: 'Date Created',
      sortable: true,
      className: 'hidden md:table-cell',
      headerClassName: 'hidden md:table-cell',
      render: (row) => (
        <span className="text-sm text-muted-foreground">
          {new Date(row.createdAt).toLocaleDateString(undefined, {
            year: 'numeric', month: 'short', day: 'numeric',
            hour: '2-digit', minute: '2-digit'
          })}
        </span>
      ),
    },
    {
      key: 'actions',
      header: 'Download',
      render: (row) => (
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="icon-sm" onClick={() => handleDownload(row._id, 'csv')} title="Download CSV">
            <FileText className="h-4 w-4 text-emerald-500" />
          </Button>
          <Button variant="ghost" size="icon-sm" onClick={() => handleDownload(row._id, 'excel')} title="Download Excel">
            <FileSpreadsheet className="h-4 w-4 text-emerald-600" />
          </Button>
          <Button variant="ghost" size="icon-sm" onClick={() => handleDownload(row._id, 'pdf')} title="Download PDF">
            <Download className="h-4 w-4 text-red-500" />
          </Button>
        </div>
      ),
    },
  ], []);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generate and download business intelligence reports."
        icon={<BarChart className="h-5 w-5" />}
      >
        <Button size="sm" onClick={() => setIsModalOpen(true)} disabled={!canManage}>
          <Plus className="h-4 w-4" />
          Generate Report
        </Button>
      </PageHeader>

      {error && (
        <Alert variant="error" onClose={() => setError(null)}>
          {error}
        </Alert>
      )}

      <DataTable
        columns={columns}
        data={reports}
        keyField="_id"
        loading={loading}
        searchable
        searchKeys={['name', 'type']}
        searchPlaceholder="Search reports by name or type…"
        pageSize={10}
        emptyIcon={<BarChart className="h-6 w-6" />}
        emptyTitle="No reports found"
        emptyDescription="Generate a new report to see it listed here."
      />

      <Modal
        open={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Generate New Report"
        description="Create a point-in-time snapshot of the selected data."
        icon={<BarChart className="h-5 w-5" />}
        footer={
          <>
            <Button variant="ghost" onClick={() => setIsModalOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleGenerate} disabled={isGenerating}>
              {isGenerating ? 'Generating…' : 'Generate Now'}
            </Button>
          </>
        }
      >
        <div className="space-y-2">
          <Label htmlFor="report-type">Report Type</Label>
          <Select
            id="report-type"
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="w-full"
          >
            <option value="inventory">Inventory Status</option>
            <option value="expiry">Expiry Forecast</option>
            <option value="recommendation">AI Recommendations</option>
          </Select>
          <p className="text-xs leading-relaxed text-muted-foreground">
            Generates a snapshot of the selected data using current database records.
          </p>
        </div>
      </Modal>
    </div>
  );
}
